name: Docker Builder

on:
  workflow_dispatch:

jobs:

  cli_docker:
    runs-on: ubuntu-latest
    permissions: ## needed to publish images to ghcr.io
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Docker Images
        run: hooks/build
        working-directory: ./docker
        env:
          DOCKER_TAG: latest
          PUSH_IMAGE: true
